<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUli7wvv\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUli7wvv/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUli7wvv.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUli7wvv\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerUli7wvv\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Uli7wvv',
    'container.build_id' => '84505329',
    'container.build_time' => 1533513167,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUli7wvv');
